// ********************************************************************************************
// *********  Manager for the airports data                ************************************
//
// Loaded from AIRPORTS_JSON_URL (in this repo as airports/airports.json)
// Note each 'airport' entry in the JSON is a LIST, so the downloaded JSON is more compact
// so the JSON includes an "airport_keys" dictionary that maps property_name -> index.
// e.g. Mifflin County is:
// ['KRVL', 40.6773872375488, -77.6268310546875, 'Mifflin Co', 'msfs_airport', 247.80239207032346, '06 24']
// and airports_data.airports_keys is:
// "airport_keys": {"ident": 0, "lat": 1, "lng": 2, "name": 3, "type": 4, "alt_m": 5, "runways": 6}
// Note the "airport_keys" data is generated by the program that creates the airports data, and we
// may add additional properties, so the key indexes could change.
//
// Downloaded airports_data is:
// {
//      "airport_keys": KEY -> INDEX dictionary for airport properties (as above)
//      "box_coords":   BOX_ID -> BOX COORDINATES dictionary for each 'box' of airports
//      "boxes": BOX_ID -> list of airports (& each airport is a list of property values)
// }
//
// The whole point of this airports_data structure is to support fast lookup of airports within
// a given lat/lng box (i.e. the map bounds).
//
// ********************************************************************************************

class B21_Airports {

    constructor(planner, map) {
        this.AIRPORTS_JSON_URL = "https://xp-soaring.github.io/tasks/b21_task_planner/airports/airports.json";
        this.DEBUG_DRAW_MAP_BOXES = false;

        this.planner = planner;
        this.map = map;
        this.airports_data = null;
        this.markers = null; // dictionary IDENT -> marker for each airport drawn on map
        this.search_ident = null; // ident of an airport search result to be highlighted on map
        this.available = false;
    }

    // init() will asynchronously download the airports data
    init() {
        fetch(this.AIRPORTS_JSON_URL).then(response => {
            if (!response.ok) {
                alert("Failed to download the airports data")
                return null;
            }
            //response.headers.set('content-type','application/json');
            return response.text();
        }).then( results => {
            console.log("airports.json loaded");
            this.airports_data = JSON.parse(results);
            this.KEY_LAT = this.airports_data.airport_keys['lat'];
            this.KEY_LNG = this.airports_data.airport_keys['lng'];
            this.KEY_NAME = this.airports_data.airport_keys['name'];
            this.KEY_IDENT = this.airports_data.airport_keys['ident'];
            this.KEY_TYPE = this.airports_data.airport_keys['type']; //"closed_airport", "heliport", "large_airport", "medium_airport", "seaplane_base", "small_airport"
            this.KEY_ALT_M = this.airports_data.airport_keys['alt_m'];
            this.KEY_RUNWAYS = this.airports_data.airport_keys['runways'];
            this.available = true;
            this.draw();
        }).catch(error => {
            console.error('Network error accessing airports.json:', error);
        });
    }

    draw() {
        this.planner.airport_markers.clearLayers();

        if (!this.available) {
            console.log("draw_airports failed");
            return;
        }

        this.markers = {};

        let zoom = this.map.getZoom();
        if ( zoom < 8) {
            console.log("Too zoomed out to display airports");
            return;
        }
        let map_bounds = this.map.getBounds();
        let map_box = { "min_lat": map_bounds.getSouth(),
                        "min_lng": map_bounds.getWest(),
                        "max_lat": map_bounds.getNorth(),
                        "max_lng": map_bounds.getEast()
        }
        console.log("draw_airports", map_box);
        for (let box_id in this.airports_data.box_coords) {
            let box = this.airports_data.box_coords[box_id];
            if (this.DEBUG_DRAW_MAP_BOXES) {
                L.rectangle([[box.min_lat,box.min_lng],[box.max_lat,box.max_lng]]).addTo(this.map);
            }
            if (this.box_overlap(box, map_box)) {
                //console.log("overlap",box_id, box);
                let airports = this.airports_data.boxes[box_id];
                for (let i=0; i<airports.length; i++) {
                    let airport = airports[i];
                    let type = airport[this.KEY_TYPE];
                    if (type.includes("airport")) {
                        let position = new L.latLng(airport[this.KEY_LAT], airport[this.KEY_LNG]);
                        let ident = airport[this.KEY_IDENT];
                        let type = airport[this.KEY_TYPE];
                        let name = airport[this.KEY_NAME].replaceAll('"',""); // Remove double quotes if original name includes those.
                        let alt_m = airport[this.KEY_ALT_M];
                        let runways = airport[this.KEY_RUNWAYS];
                        let circle_radius = 3 * (zoom - 7);
                        if (type=="large_airport") {
                            circle_radius *= 3;
                        } else if (type=="medium_airport") {
                            circle_radius *= 2;
                        }
                        let marker = L.circleMarker(position, {
                            renderer: this.planner.canvas_renderer,
                            color: this.planner.task.is_msfs_airport(type) ? '#3388ff' : '#33ff88',
                            radius: circle_radius
                        });
                        marker.addTo(this.planner.airport_markers);
                        marker.bindPopup(name+"<br/>"+type+"<br/>"+ident);
                        marker.on('mouseover', function(event){
                            marker.openPopup();
                        });
                        marker.on('mouseout', function(event){
                            marker.closePopup();
                        });
                        marker.on('click', (e) => {
                            console.log("User click:",ident,name);
                            this.planner.task.add_new_poi(position, type, {"ident": ident, "name": name, "alt_m": alt_m, "runways": runways});
                        });
                        if (ident == this.search_ident) {
                            marker.openPopup();
                            this.search_ident = null;
                        }
                        //this.markers[ident] = marker;
                    }
                }
            }
        }
    }

    box_overlap(box, map_box) {
        if (map_box.min_lat > box.max_lat) {
            return false;
        }
        if (map_box.max_lat < box.min_lat) {
            return false;
        }
        if (map_box.min_lng > box.max_lng) {
            return false;
        }
        if (map_box.max_lng < box.min_lng) {
            return false;
        }
        return true;
    }

    // User has typed in search box
    //DEBUG pan the map to the clicked airport result, and highlight that airport
    search(search_value, results_el) {
        let parent = this;
        const RESULTS_MAX = 100;
        let results = [];
        for (let box_id in this.airports_data.box_coords) {
            let airports = this.airports_data.boxes[box_id];
            for (let i=0; i<airports.length; i++) {
                let airport = airports[i];
                let type = airport[this.KEY_TYPE];
                if (type.includes("airport")) {
                    let ident = airport[this.KEY_IDENT];
                    let name = airport[this.KEY_NAME].replaceAll('"',""); // Remove double quotes if original name includes those.
                    if ((ident+name).toLowerCase().includes(search_value)) {
                        results.push(airport);
                        if (results.length > RESULTS_MAX) {
                            break;
                        }
                    }
                }
            }
            if (results.length > RESULTS_MAX) {
                break;
            }
        }
        if (results.length>0) {
            while (results_el.firstChild) {
                results_el.removeChild(results_el.lastChild);
            }
            results_el.style.display = "block";
            for (let i=0;i<results.length;i++) {
                let airport = results[i];
                let result_el = document.createElement("div");
                result_el.className = "search_result";
                result_el.onclick = (e) => {
                    results_el.style.display = "none";
                    parent.clicked(parent, airport);
                }
                result_el.innerHTML = (airport[this.KEY_IDENT]+" "+airport[this.KEY_NAME]).replaceAll(" ","&nbsp;");
                results_el.appendChild(result_el);
            }
        }
        console.log("Search results", results.length);
    }

    clicked(parent, airport) {
        console.log("result clicked", airport);
        let lat = airport[parent.KEY_LAT];
        let lng = airport[parent.KEY_LNG];
        // Set the search_ident so draw() knows the redraw is due to a search and can highlight the airport on map
        parent.search_ident = airport[parent.KEY_IDENT];
        this.map.panTo([lat,lng]);
    }

} // end class B21_Airports
