
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/albatross_500/Race-500-Pratzschwitz.pln
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/albatross_500/AS33_Attila_2022-07-30T17-11-26.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/albatross_500/AS33_Attila_2022-08-01T14-09-14.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/albatross_500/AS33_gofaster_2022-08-01T02-51-32.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/albatross_500/AS33_Topher_2022-09-05T06-54-48.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/albatross_500/DG808S_ANRI_2022-07-29T12-28-42.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/albatross_500/DG808S_ANRI_2022-08-04T17-13-37.gpx
