
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/husbos110km/HusBos 110km.pln
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/husbos110km/2022-07-15 HusBos 110km AS33.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/husbos110km/2022-09-11 HusBos 110km AS33.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/husbos110km/2022-08-08 HusBos 110km LS4 dry.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/husbos110km/2022-08-10 HusBos 110km LS4 dry.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/husbos110km/2022-08-22 HusBos 110km LS4 wet B21.gpx
https://xp-soaring.github.io/tasks/b21_task_planner/testing/files_comp/husbos110km/2022-09-12 HusBos 110km Discus 2c wet.gpx
